name: PHP Code Style

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cs:
    runs-on: ubuntu-latest
    name: PHP-CS-Fixer
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: cs2pr
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHP-CS-Fixer
        run: composer run cs:check
